language: python

matrix:
  include:
    - name: "Python 3.5 on Ubuntu 16.04 amd64"
      python: 3.5
      arch: amd64
      os: linux
      dist: xenial
    - name: "Python 3.5 on Ubuntu 16.04 arm64"
      python: 3.5
      arch: arm64
      os: linux
      dist: xenial
    - name: "Python 3.6 on Ubuntu 18.04 amd64"
      python: 3.6
      arch: amd64
      os: linux
      dist: bionic
    - name: "Python 3.7 on Ubuntu 18.04 amd64"
      python: 3.7
      arch: amd64
      os: linux
      dist: bionic
    - name: "Python 3.8 on Ubuntu 20.04 amd64"
      python: 3.8
      arch: amd64
      os: linux
      dist: focal

branches:
  only:
    - main

services:
  - docker

before_install:

install:
  - pip install -e .

script:
  - python test.py
